export function getmetrics(char) {

    let metrics = [{
        name: "A",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Aacute",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Abreve",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Acaron",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Acircumflex",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Adieresis",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Agrave",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Amacron",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Aogonek",
        width: 592,
        lsb: 20,
        rsb: -28
    }, {
        name: "Aring",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Atilde",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "AE",
        width: 796,
        lsb: 6,
        rsb: 49
    }, {
        name: "B",
        width: 532,
        lsb: 77,
        rsb: 58
    }, {
        name: "C",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "Cacute",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "Ccaron",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "Ccedilla",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "Cdotaccent",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "D",
        width: 568,
        lsb: 77,
        rsb: 50
    }, {
        name: "Eth",
        width: 536,
        lsb: -19,
        rsb: 50
    }, {
        name: "Dcaron",
        width: 568,
        lsb: 77,
        rsb: 50
    }, {
        name: "Dcroat",
        width: 536,
        lsb: -19,
        rsb: 50
    }, {
        name: "Ddotbelow",
        width: 568,
        lsb: 77,
        rsb: 50
    }, {
        name: "Dmacronbelow",
        width: 568,
        lsb: 77,
        rsb: 50
    }, {
        name: "E",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Eacute",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Ecaron",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Ecircumflex",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Edieresis",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Edotaccent",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Egrave",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Emacron",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Eogonek",
        width: 473,
        lsb: 76,
        rsb: 20
    }, {
        name: "Etilde",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Schwa",
        width: 700,
        lsb: 97,
        rsb: 87
    }, {
        name: "F",
        width: 477,
        lsb: 77,
        rsb: 53
    }, {
        name: "G",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "Gbreve",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "Gcaron",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "Gcommaaccent",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "Gdotaccent",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "Gmacron",
        width: 586,
        lsb: 50,
        rsb: 66
    }, {
        name: "H",
        width: 572,
        lsb: 77,
        rsb: 72
    }, {
        name: "Hbar",
        width: 645,
        lsb: 15,
        rsb: 20
    }, {
        name: "Hbrevebelow",
        width: 572,
        lsb: 77,
        rsb: 72
    }, {
        name: "Hdotbelow",
        width: 572,
        lsb: 77,
        rsb: 72
    }, {
        name: "I",
        width: 154,
        lsb: 77,
        rsb: 77
    }, {
        name: "IJ",
        width: 546,
        lsb: 77,
        rsb: 77
    }, {
        name: "Iacute",
        width: 154,
        lsb: 27,
        rsb: -44
    }, {
        name: "Icaron",
        width: 154,
        lsb: -30,
        rsb: -29
    }, {
        name: "Icircumflex",
        width: 154,
        lsb: -30,
        rsb: -37
    }, {
        name: "Idieresis",
        width: 154,
        lsb: -29,
        rsb: -22
    }, {
        name: "Idotaccent",
        width: 154,
        lsb: 75,
        rsb: 77
    }, {
        name: "Igrave",
        width: 154,
        lsb: -44,
        rsb: 27
    }, {
        name: "Imacron",
        width: 154,
        lsb: -71,
        rsb: -70
    }, {
        name: "Iogonek",
        width: 154,
        lsb: -14,
        rsb: 29
    }, {
        name: "Itilde",
        width: 154,
        lsb: -67,
        rsb: -66
    }, {
        name: "J",
        width: 392,
        lsb: 24,
        rsb: 77
    }, {
        name: "Jacute",
        width: 392,
        lsb: 24,
        rsb: -44
    }, {
        name: "K",
        width: 474,
        lsb: 77,
        rsb: 16
    }, {
        name: "Kcommaaccent",
        width: 491,
        lsb: 77,
        rsb: 33
    }, {
        name: "Kmacronbelow",
        width: 491,
        lsb: 77,
        rsb: 33
    }, {
        name: "L",
        width: 491,
        lsb: 77,
        rsb: 16
    }, {
        name: "Lacute",
        width: 491,
        lsb: 27,
        rsb: 16
    }, {
        name: "Lcaron",
        width: 491,
        lsb: 77,
        rsb: 16
    }, {
        name: "Lcommaaccent",
        width: 491,
        lsb: 77,
        rsb: 16
    }, {
        name: "Lslash",
        width: 518,
        lsb: -17,
        rsb: 16
    }, {
        name: "M",
        width: 689,
        lsb: 78,
        rsb: 78
    }, {
        name: "N",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "Nacute",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "Ncaron",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "Ncommaaccent",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "Ntilde",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "O",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Oacute",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Ocaron",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Ocircumflex",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Odieresis",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Ograve",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Ohungarumlaut",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Omacron",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Oslash",
        width: 626,
        lsb: 50,
        rsb: 51
    }, {
        name: "Otilde",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "OE",
        width: 971,
        lsb: 50,
        rsb: 49
    }, {
        name: "P",
        width: 518,
        lsb: 77,
        rsb: 36
    }, {
        name: "Thorn",
        width: 469,
        lsb: 76,
        rsb: 36
    }, {
        name: "Q",
        width: 645,
        lsb: 50,
        rsb: -43
    }, {
        name: "R",
        width: 510,
        lsb: 77,
        rsb: 25
    }, {
        name: "Racute",
        width: 510,
        lsb: 77,
        rsb: 25
    }, {
        name: "Rcaron",
        width: 510,
        lsb: 77,
        rsb: 25
    }, {
        name: "Rcommaaccent",
        width: 510,
        lsb: 77,
        rsb: 25
    }, {
        name: "S",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Sacute",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Saltillo",
        width: 180,
        lsb: 90,
        rsb: 90
    }, {
        name: "Scaron",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Scedilla",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Scommaaccent",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Sdotbelow",
        width: 510,
        lsb: 58,
        rsb: 43
    }, {
        name: "Germandbls",
        width: 567,
        lsb: 95,
        rsb: 65
    }, {
        name: "T",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "Tcaron",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "Tcedilla",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "Tcommaaccent",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "Tdotbelow",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "Tmacronbelow",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "U",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Uacute",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Ucaron",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Ucircumflex",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Udieresis",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Udieresisacute",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Udieresiscaron",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Udieresisgrave",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Udieresismacron",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Ugrave",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Uhungarumlaut",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Umacron",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Uogonek",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Uring",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "Utilde",
        width: 556,
        lsb: 66,
        rsb: 66
    }, {
        name: "V",
        width: 591,
        lsb: 20,
        rsb: 20
    }, {
        name: "W",
        width: 845,
        lsb: 43,
        rsb: 43
    }, {
        name: "Wacute",
        width: 845,
        lsb: 43,
        rsb: 43
    }, {
        name: "Wcircumflex",
        width: 845,
        lsb: 43,
        rsb: 43
    }, {
        name: "Wdieresis",
        width: 845,
        lsb: 43,
        rsb: 43
    }, {
        name: "Wgrave",
        width: 845,
        lsb: 43,
        rsb: 43
    }, {
        name: "X",
        width: 512,
        lsb: 21,
        rsb: 21
    }, {
        name: "Y",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Yacute",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Ycircumflex",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Ydieresis",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Ygrave",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Ymacron",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Ytilde",
        width: 505,
        lsb: 17,
        rsb: 18
    }, {
        name: "Z",
        width: 543,
        lsb: 38,
        rsb: 45
    }, {
        name: "Zacute",
        width: 543,
        lsb: 38,
        rsb: 45
    }, {
        name: "Zcaron",
        width: 543,
        lsb: 38,
        rsb: 45
    }, {
        name: "Zdotaccent",
        width: 543,
        lsb: 38,
        rsb: 45
    }, {
        name: "Zdotbelow",
        width: 543,
        lsb: 38,
        rsb: 45
    }, {
        name: "Lcommaaccent.loclMAH",
        width: 491,
        lsb: 77,
        rsb: 16
    }, {
        name: "Ncommaaccent.loclMAH",
        width: 602,
        lsb: 77,
        rsb: 77
    }, {
        name: "a",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "aacute",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "abreve",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "acaron",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "acircumflex",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "adieresis",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "agrave",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "amacron",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "aogonek",
        width: 443,
        lsb: 58,
        rsb: 6
    }, {
        name: "aring",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "atilde",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "ae",
        width: 815,
        lsb: 58,
        rsb: 60
    }, {
        name: "b",
        width: 505,
        lsb: 69,
        rsb: 50
    }, {
        name: "c",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "cacute",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "ccaron",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "ccedilla",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "cdotaccent",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "d",
        width: 505,
        lsb: 50,
        rsb: 69
    }, {
        name: "eth",
        width: 496,
        lsb: 40,
        rsb: 47
    }, {
        name: "dcaron",
        width: 578,
        lsb: 50,
        rsb: -29
    }, {
        name: "dcroat",
        width: 500,
        lsb: 50,
        rsb: -27
    }, {
        name: "ddotbelow",
        width: 505,
        lsb: 50,
        rsb: 69
    }, {
        name: "dmacronbelow",
        width: 505,
        lsb: 50,
        rsb: 69
    }, {
        name: "e",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "eacute",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "ecaron",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "ecircumflex",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "edieresis",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "edotaccent",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "egrave",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "emacron",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "eogonek",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "etilde",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "schwa",
        width: 476,
        lsb: 58,
        rsb: 48
    }, {
        name: "f",
        width: 356,
        lsb: 42,
        rsb: 13
    }, {
        name: "g",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "gbreve",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "gcaron",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "gcommaaccent",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "gdotaccent",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "gmacron",
        width: 517,
        lsb: 50,
        rsb: 77
    }, {
        name: "h",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "hbar",
        width: 495,
        lsb: 25,
        rsb: 70
    }, {
        name: "hbrevebelow",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "hdotbelow",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "hmacronbelow",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "i",
        width: 190,
        lsb: 93,
        rsb: 95
    }, {
        name: "idotless",
        width: 190,
        lsb: 95,
        rsb: 95
    }, {
        name: "iacute",
        width: 190,
        lsb: 45,
        rsb: -26
    }, {
        name: "icaron",
        width: 190,
        lsb: -12,
        rsb: -11
    }, {
        name: "icircumflex",
        width: 190,
        lsb: -12,
        rsb: -19
    }, {
        name: "idieresis",
        width: 190,
        lsb: -11,
        rsb: -4
    }, {
        name: "idotaccent",
        width: 190,
        lsb: 93,
        rsb: 95
    }, {
        name: "igrave",
        width: 190,
        lsb: -26,
        rsb: 45
    }, {
        name: "ij",
        width: 190,
        lsb: 93,
        rsb: 95
    }, {
        name: "imacron",
        width: 190,
        lsb: -53,
        rsb: -52
    }, {
        name: "iogonek",
        width: 190,
        lsb: 4,
        rsb: 47
    }, {
        name: "itilde",
        width: 190,
        lsb: -49,
        rsb: -48
    }, {
        name: "j",
        width: 209,
        lsb: -72,
        rsb: 95
    }, {
        name: "jdotless",
        width: 209,
        lsb: -72,
        rsb: 95
    }, {
        name: "jacute",
        width: 209,
        lsb: -72,
        rsb: -26
    }, {
        name: "k",
        width: 399,
        lsb: 80,
        rsb: 16
    }, {
        name: "kcommaaccent",
        width: 430,
        lsb: 80,
        rsb: 47
    }, {
        name: "kmacronbelow",
        width: 430,
        lsb: 73,
        rsb: 47
    }, {
        name: "l",
        width: 154,
        lsb: 77,
        rsb: 77
    }, {
        name: "lacute",
        width: 154,
        lsb: 27,
        rsb: -44
    }, {
        name: "lcaron",
        width: 154,
        lsb: 77,
        rsb: -524
    }, {
        name: "lcommaaccent",
        width: 154,
        lsb: 6,
        rsb: 69
    }, {
        name: "lslash",
        width: 187,
        lsb: -19,
        rsb: -19
    }, {
        name: "m",
        width: 715,
        lsb: 77,
        rsb: 69
    }, {
        name: "n",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "nacute",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "ncaron",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "ncommaaccent",
        width: 481,
        lsb: 77,
        rsb: 70
    }, {
        name: "ntilde",
        width: 481,
        lsb: 77,
        rsb: 68
    }, {
        name: "o",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "oacute",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "ocaron",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "ocircumflex",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "odieresis",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "ograve",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "ohungarumlaut",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "omacron",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "oslash",
        width: 527,
        lsb: 52,
        rsb: 52
    }, {
        name: "otilde",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "oe",
        width: 869,
        lsb: 50,
        rsb: 58
    }, {
        name: "p",
        width: 505,
        lsb: 69,
        rsb: 50
    }, {
        name: "thorn",
        width: 505,
        lsb: 69,
        rsb: 50
    }, {
        name: "q",
        width: 505,
        lsb: 50,
        rsb: 69
    }, {
        name: "r",
        width: 322,
        lsb: 77,
        rsb: 10
    }, {
        name: "racute",
        width: 322,
        lsb: 77,
        rsb: 10
    }, {
        name: "rcaron",
        width: 322,
        lsb: 66,
        rsb: 10
    }, {
        name: "rcommaaccent",
        width: 322,
        lsb: 6,
        rsb: 10
    }, {
        name: "s",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "sacute",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "saltillo",
        width: 600,
        lsb: 300,
        rsb: 300
    }, {
        name: "scaron",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "scedilla",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "scommaaccent",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "sdotbelow",
        width: 434,
        lsb: 43,
        rsb: 50
    }, {
        name: "germandbls",
        width: 479,
        lsb: 77,
        rsb: 35
    }, {
        name: "t",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "tcaron",
        width: 414,
        lsb: 34,
        rsb: -79
    }, {
        name: "tcedilla",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "tcommaaccent",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "tdieresis",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "tdotbelow",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "tmacronbelow",
        width: 414,
        lsb: 34,
        rsb: 39
    }, {
        name: "u",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "uacute",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "ucaron",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "ucircumflex",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "udieresis",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "udieresisacute",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "udieresiscaron",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "udieresisgrave",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "udieresismacron",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "ugrave",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "uhungarumlaut",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "umacron",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "uogonek",
        width: 481,
        lsb: 70,
        rsb: 32
    }, {
        name: "uring",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "utilde",
        width: 481,
        lsb: 70,
        rsb: 77
    }, {
        name: "v",
        width: 438,
        lsb: 16,
        rsb: 17
    }, {
        name: "w",
        width: 678,
        lsb: 20,
        rsb: 20
    }, {
        name: "wacute",
        width: 678,
        lsb: 20,
        rsb: 20
    }, {
        name: "wcircumflex",
        width: 678,
        lsb: 20,
        rsb: 20
    }, {
        name: "wdieresis",
        width: 678,
        lsb: 20,
        rsb: 20
    }, {
        name: "wgrave",
        width: 678,
        lsb: 20,
        rsb: 20
    }, {
        name: "x",
        width: 425,
        lsb: 32,
        rsb: 33
    }, {
        name: "y",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "yacute",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ycircumflex",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ydieresis",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ygrave",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ymacron",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ytilde",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "z",
        width: 491,
        lsb: 57,
        rsb: 53
    }, {
        name: "zacute",
        width: 491,
        lsb: 57,
        rsb: 53
    }, {
        name: "zcaron",
        width: 491,
        lsb: 57,
        rsb: 53
    }, {
        name: "zdotaccent",
        width: 491,
        lsb: 57,
        rsb: 53
    }, {
        name: "zdotbelow",
        width: 491,
        lsb: 57,
        rsb: 53
    }, {
        name: "ordfeminine",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "ordmasculine",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "A-cy",
        width: 592,
        lsb: 20,
        rsb: 20
    }, {
        name: "Be-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ve-cy",
        width: 532,
        lsb: 77,
        rsb: 58
    }, {
        name: "Ge-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "De-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ie-cy",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Io-cy",
        width: 473,
        lsb: 76,
        rsb: 49
    }, {
        name: "Zhe-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ze-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ii-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Iishort-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ka-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "El-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Em-cy",
        width: 689,
        lsb: 78,
        rsb: 78
    }, {
        name: "En-cy",
        width: 572,
        lsb: 77,
        rsb: 72
    }, {
        name: "O-cy",
        width: 625,
        lsb: 50,
        rsb: 50
    }, {
        name: "Pe-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Er-cy",
        width: 518,
        lsb: 77,
        rsb: 36
    }, {
        name: "Es-cy",
        width: 528,
        lsb: 50,
        rsb: 43
    }, {
        name: "Te-cy",
        width: 536,
        lsb: 15,
        rsb: 15
    }, {
        name: "U-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ef-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ha-cy",
        width: 512,
        lsb: 21,
        rsb: 21
    }, {
        name: "Che-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Tse-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Sha-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Shcha-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Softsign-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Yeru-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Hardsign-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ereversed-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Yu-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Ya-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "a-cy",
        width: 443,
        lsb: 58,
        rsb: 53
    }, {
        name: "be-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ve-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ge-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "de-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ie-cy",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "io-cy",
        width: 476,
        lsb: 48,
        rsb: 58
    }, {
        name: "zhe-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ze-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ii-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "iishort-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ka-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "el-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "em-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "en-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "o-cy",
        width: 503,
        lsb: 50,
        rsb: 50
    }, {
        name: "pe-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "er-cy",
        width: 505,
        lsb: 69,
        rsb: 50
    }, {
        name: "es-cy",
        width: 454,
        lsb: 50,
        rsb: 47
    }, {
        name: "te-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "u-cy",
        width: 475,
        lsb: 15,
        rsb: 16
    }, {
        name: "ef-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ha-cy",
        width: 425,
        lsb: 32,
        rsb: 33
    }, {
        name: "che-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "tse-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "sha-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "shcha-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "softsign-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "yeru-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "hardsign-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ereversed-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "yu-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ya-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "Omega",
        width: 680,
        lsb: 53,
        rsb: 53
    }, {
        name: "pi",
        width: 642,
        lsb: 23,
        rsb: 38
    }, {
        name: "zero",
        width: 550,
        lsb: 62,
        rsb: 62
    }, {
        name: "one",
        width: 632,
        lsb: 148,
        rsb: 279
    }, {
        name: "two",
        width: 576,
        lsb: 92,
        rsb: 91
    }, {
        name: "three",
        width: 594,
        lsb: 88,
        rsb: 111
    }, {
        name: "four",
        width: 597,
        lsb: 53,
        rsb: 53
    }, {
        name: "five",
        width: 601,
        lsb: 104,
        rsb: 103
    }, {
        name: "six",
        width: 578,
        lsb: 92,
        rsb: 77
    }, {
        name: "seven",
        width: 589,
        lsb: 76,
        rsb: 80
    }, {
        name: "eight",
        width: 593,
        lsb: 79,
        rsb: 79
    }, {
        name: "nine",
        width: 578,
        lsb: 77,
        rsb: 92
    }, {
        name: "space",
        width: 280,
        lsb: 0,
        rsb: 0
    }, {
        name: "nbspace",
        width: 280,
        lsb: 0,
        rsb: 0
    }, {
        name: "period",
        width: 184,
        lsb: 92,
        rsb: 92
    }, {
        name: "comma",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "colon",
        width: 184,
        lsb: 92,
        rsb: 92
    }, {
        name: "semicolon",
        width: 260,
        lsb: 92,
        rsb: 92
    }, {
        name: "ellipsis",
        width: 226,
        lsb: 113,
        rsb: 113
    }, {
        name: "exclam",
        width: 192,
        lsb: 96,
        rsb: 96
    }, {
        name: "exclamdown",
        width: 192,
        lsb: 96,
        rsb: 96
    }, {
        name: "question",
        width: 483,
        lsb: 66,
        rsb: 96
    }, {
        name: "questiondown",
        width: 483,
        lsb: 96,
        rsb: 66
    }, {
        name: "periodcentered",
        width: 588,
        lsb: 269,
        rsb: 269
    }, {
        name: "bullet",
        width: 350,
        lsb: 125,
        rsb: 125
    }, {
        name: "asterisk",
        width: 501,
        lsb: 39,
        rsb: 40
    }, {
        name: "numbersign",
        width: 615,
        lsb: 30,
        rsb: 30
    }, {
        name: "slash",
        width: 412,
        lsb: 29,
        rsb: 29
    }, {
        name: "backslash",
        width: 412,
        lsb: 29,
        rsb: 29
    }, {
        name: "hyphen",
        width: 416,
        lsb: 38,
        rsb: 38
    }, {
        name: "softhyphen",
        width: 580,
        lsb: 38,
        rsb: 202
    }, {
        name: "endash",
        width: 525,
        lsb: 30,
        rsb: 30
    }, {
        name: "emdash",
        width: 1035,
        lsb: 30,
        rsb: 30
    }, {
        name: "underscore",
        width: 540,
        lsb: 30,
        rsb: 30
    }, {
        name: "parenleft",
        width: 354,
        lsb: 92,
        rsb: 71
    }, {
        name: "parenright",
        width: 354,
        lsb: 71,
        rsb: 92
    }, {
        name: "braceleft",
        width: 436,
        lsb: 102,
        rsb: 114
    }, {
        name: "braceright",
        width: 436,
        lsb: 114,
        rsb: 102
    }, {
        name: "bracketleft",
        width: 436,
        lsb: 119,
        rsb: 87
    }, {
        name: "bracketright",
        width: 436,
        lsb: 87,
        rsb: 119
    }, {
        name: "quotesinglbase",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "quotedblbase",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "quotedblleft",
        width: 379,
        lsb: 92,
        rsb: 92
    }, {
        name: "quotedblright",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "quoteleft",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "quoteright",
        width: 253,
        lsb: 92,
        rsb: 92
    }, {
        name: "guillemetleft",
        width: 519,
        lsb: 48,
        rsb: 94
    }, {
        name: "guillemetright",
        width: 519,
        lsb: 94,
        rsb: 48
    }, {
        name: "guilsinglleft",
        width: 249,
        lsb: 48,
        rsb: 42
    }, {
        name: "guilsinglright",
        width: 249,
        lsb: 42,
        rsb: 48
    }, {
        name: "quotedbl",
        width: 336,
        lsb: 96,
        rsb: 96
    }, {
        name: "quotesingle",
        width: 176,
        lsb: 88,
        rsb: 88
    }, {
        name: "florin",
        width: 566,
        lsb: 135,
        rsb: 83
    }, {
        name: "at",
        width: 841,
        lsb: 66,
        rsb: 66
    }, {
        name: "ampersand",
        width: 609,
        lsb: 43,
        rsb: 52
    }, {
        name: "section",
        width: 552,
        lsb: 71,
        rsb: 97
    }, {
        name: "copyright",
        width: 786,
        lsb: 43,
        rsb: 43
    }, {
        name: "registered",
        width: 786,
        lsb: 43,
        rsb: 43
    }, {
        name: "trademark",
        width: 1225,
        lsb: 15,
        rsb: 78
    }, {
        name: "degree",
        width: 356,
        lsb: 43,
        rsb: 43
    }, {
        name: "bar",
        width: 176,
        lsb: 88,
        rsb: 88
    }, {
        name: "brokenbar",
        width: 176,
        lsb: 88,
        rsb: 88
    }, {
        name: "dagger",
        width: 595,
        lsb: 121,
        rsb: 121
    }, {
        name: "daggerdbl",
        width: 600,
        lsb: 121,
        rsb: 121
    }, {
        name: "paragraph",
        width: 476,
        lsb: 44,
        rsb: 22
    }, {
        name: "cent",
        width: 575,
        lsb: 98,
        rsb: 120
    }, {
        name: "currency",
        width: 536,
        lsb: 46,
        rsb: 45
    }, {
        name: "dollar",
        width: 549,
        lsb: 79,
        rsb: 87
    }, {
        name: "euro",
        width: 580,
        lsb: 29,
        rsb: 51
    }, {
        name: "sterling",
        width: 663,
        lsb: 80,
        rsb: 109
    }, {
        name: "yen",
        width: 554,
        lsb: 42,
        rsb: 42
    }, {
        name: "plus",
        width: 592,
        lsb: 61,
        rsb: 61
    }, {
        name: "minus",
        width: 592,
        lsb: 61,
        rsb: 61
    }, {
        name: "multiply",
        width: 522,
        lsb: 65,
        rsb: 65
    }, {
        name: "divide",
        width: 592,
        lsb: 61,
        rsb: 61
    }, {
        name: "equal",
        width: 592,
        lsb: 61,
        rsb: 61
    }, {
        name: "notequal",
        width: 592,
        lsb: 61,
        rsb: 61
    }, {
        name: "greater",
        width: 566,
        lsb: 61,
        rsb: 61
    }, {
        name: "less",
        width: 566,
        lsb: 61,
        rsb: 61
    }, {
        name: "greaterequal",
        width: 601,
        lsb: 61,
        rsb: 61
    }, {
        name: "lessequal",
        width: 601,
        lsb: 61,
        rsb: 61
    }, {
        name: "plusminus",
        width: 601,
        lsb: 61,
        rsb: 61
    }, {
        name: "approxequal",
        width: 553,
        lsb: 66,
        rsb: 66
    }, {
        name: "asciitilde",
        width: 553,
        lsb: 66,
        rsb: 66
    }, {
        name: "logicalnot",
        width: 561,
        lsb: 61,
        rsb: 66
    }, {
        name: "asciicircum",
        width: 456,
        lsb: 67,
        rsb: 67
    }, {
        name: "infinity",
        width: 518,
        lsb: 35,
        rsb: 35
    }, {
        name: "integral",
        width: 528,
        lsb: 43,
        rsb: 43
    }, {
        name: "increment",
        width: 580,
        lsb: 71,
        rsb: 84
    }, {
        name: "product",
        width: 586,
        lsb: 38,
        rsb: 38
    }, {
        name: "summation",
        width: 488,
        lsb: 30,
        rsb: 30
    }, {
        name: "radical",
        width: 595,
        lsb: 58,
        rsb: 26
    }, {
        name: "micro",
        width: 543,
        lsb: 89,
        rsb: 15
    }, {
        name: "partialdiff",
        width: 504,
        lsb: 62,
        rsb: 62
    }, {
        name: "percent",
        width: 640,
        lsb: 35,
        rsb: 35
    }, {
        name: "perthousand",
        width: 936,
        lsb: 35,
        rsb: 35
    }, {
        name: "lozenge",
        width: 544,
        lsb: 67,
        rsb: 67
    }, {
        name: "brevecomb-cy",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "dieresiscomb",
        width: 600,
        lsb: 183,
        rsb: 212
    }, {
        name: "dotaccentcomb",
        width: 600,
        lsb: 299,
        rsb: 301
    }, {
        name: "gravecomb",
        width: 600,
        lsb: 184,
        rsb: 245
    }, {
        name: "acutecomb",
        width: 600,
        lsb: 184,
        rsb: 245
    }, {
        name: "hungarumlautcomb",
        width: 600,
        lsb: 220,
        rsb: 179
    }, {
        name: "caroncomb.alt",
        width: 600,
        lsb: 358,
        rsb: 179
    }, {
        name: "circumflexcomb",
        width: 600,
        lsb: 192,
        rsb: 187
    }, {
        name: "caroncomb",
        width: 600,
        lsb: 192,
        rsb: 195
    }, {
        name: "brevecomb",
        width: 600,
        lsb: 227,
        rsb: 140
    }, {
        name: "ringcomb",
        width: 600,
        lsb: 233,
        rsb: 204
    }, {
        name: "tildecomb",
        width: 600,
        lsb: 168,
        rsb: 145
    }, {
        name: "macroncomb",
        width: 600,
        lsb: 177,
        rsb: 128
    }, {
        name: "commaturnedabovecomb",
        width: 300,
        lsb: 152,
        rsb: 79
    }, {
        name: "dotbelowcomb",
        width: 600,
        lsb: 299,
        rsb: 301
    }, {
        name: "commaaccentcomb",
        width: 600,
        lsb: 242,
        rsb: 279
    }, {
        name: "cedillacomb",
        width: 600,
        lsb: 200,
        rsb: 242
    }, {
        name: "ogonekcomb",
        width: 600,
        lsb: 250,
        rsb: 211
    }, {
        name: "brevebelowcomb",
        width: 600,
        lsb: 177,
        rsb: 190
    }, {
        name: "macronbelowcomb",
        width: 600,
        lsb: 177,
        rsb: 128
    }, {
        name: "dieresis",
        width: 468,
        lsb: 149,
        rsb: 149
    }, {
        name: "dotaccent",
        width: 510,
        lsb: 255,
        rsb: 255
    }, {
        name: "grave",
        width: 511,
        lsb: 151,
        rsb: 189
    }, {
        name: "acute",
        width: 511,
        lsb: 151,
        rsb: 189
    }, {
        name: "hungarumlaut",
        width: 1252,
        lsb: 0,
        rsb: 0
    }, {
        name: "circumflex",
        width: 535,
        lsb: 157,
        rsb: 157
    }, {
        name: "caron",
        width: 535,
        lsb: 157,
        rsb: 157
    }, {
        name: "breve",
        width: 1204,
        lsb: 0,
        rsb: 0
    }, {
        name: "ring",
        width: 583,
        lsb: 210,
        rsb: 210
    }, {
        name: "tilde",
        width: 569,
        lsb: 141,
        rsb: 141
    }, {
        name: "macron",
        width: 1236,
        lsb: 0,
        rsb: 0
    }, {
        name: "cedilla",
        width: 582,
        lsb: 212,
        rsb: 212
    }, {
        name: "ogonek",
        width: 1448,
        lsb: 0,
        rsb: 0
    }, {
        name: "apostrophemod",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "commareversedmod",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ringhalfleft",
        width: 600,
        lsb: 0,
        rsb: 0
    }, {
        name: "ringhalfright",
        width: 600,
        lsb: 0,
        rsb: 0
    }]

    const glyph = metrics.find(({ name }) => name === char);

    return glyph;

}